[build]
  functions = "functions-build"
  command = "npm run build"
  publish = "dist"

[dev]
  framework = "#custom"
  command = "npm run dev-all"
  targetPort = 3000

[template.environment]
  FAUNA_SECRET_KEY = "Your FaunaDB Server Secret"
